# Generated by Django 4.2.16 on 2024-11-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0003_alter_voter_v21primary_alter_voter_v21town_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='precinct_number',
            field=models.CharField(max_length=10),
        ),
    ]
