# Generated by Django 4.2.16 on 2024-11-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0007_remove_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
