# Generated by Django 4.2.16 on 2024-11-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0009_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_file',
        ),
    ]
